# Unifier config TOML

[system]
debug = false
package = "unifier"
language = "english"
skip_status_check = false
encrypted_env_salt = 10 # change this to whatever you want, as long as the bot doesn't crash

[roles]
owner = -1
other_owners = [] # NOTE: Unless you need multiple people to manage your Unifier instance, we recommend leaving this empty.
admin_ids = []

[roles.owner_external]
# For each platform, you can add your account's ID here.
revolt = ""
guilded = ""

[bot]
prefix = "u!"
ping = 0
main_color = "ed4545"
custom_slogan = ""

[backups]
compress_cache = true
cache_backup_limit = 10000
periodic_backup = 0
periodic_backup_cloud = 0
cloud_backup_endpoint = ""
cloud_backup_salt = 12

[plugin]
branch = "main"
repo = "https://github.com/UnifierHQ/unifier"
check_endpoint = "https://github.com/UnifierHQ/unifier-version.git"
files_endpoint = "https://github.com/UnifierHQ"

[moderation]
enable_logging = false
enable_reporting = false
enable_rtt = true
logging_edit = false
logging_delete = false
home_guild = -1
logs_channel = -1
reports_channel = -1
moderator_role = -1

[bridge]
use_multicore = true
allow_posts = false
enable_exp = false
exp_cooldown = 30
existence_wait = 0
enable_emoji_tags = false
enable_ctx_commands = true
enable_rotating_status = true
enable_seasonal_status = true # Rotating status must be enabled for this to have any effect.
custom_status_messages = [] # example: [["custom", "just living life"], ["playing", "with messages"]]
enable_safety_alerts = false
safe_filetypes = true
suppress_filesize_warning = false
global_filesize_limit = 0 # This will be used if it's lower than the platform's filesize limit and vice versa. Set to 0 to disable.
permanent_invites = false
enable_private_rooms = false
private_rooms_mod_access = true # Disable this if you don't want moderators to access Private Rooms.
private_rooms_limit = 0
main_room = "main"
alerts_room = "alerts"
posts_room = "posts"
posts_ref_room = "post-comments"

[legal]
terms_url = "" # Add a link to your Terms of Service document here
privacy_url = "" # Add a link to your Privacy Policy document here